/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WspIssuesRouteImport } from './routes/wsp-issues'
import { Route as WspInTransitRouteImport } from './routes/wsp-in-transit'
import { Route as WdTransferRouteImport } from './routes/wd-transfer'
import { Route as WdStockTrackRouteImport } from './routes/wd-stock-track'
import { Route as WdIssueTlRouteImport } from './routes/wd-issue-tl'
import { Route as WdIssueRouteImport } from './routes/wd-issue'
import { Route as WdRouteImport } from './routes/wd'
import { Route as TlRouteImport } from './routes/tl'
import { Route as StockRouteImport } from './routes/stock'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as MyWdsRouteImport } from './routes/my-wds'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as LossesRouteImport } from './routes/losses'
import { Route as LossApprovalsRouteImport } from './routes/loss-approvals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConcernsRouteImport } from './routes/concerns'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WdAdminUsersRouteImport } from './routes/wd-admin.users'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminHierarchyRouteImport } from './routes/admin.hierarchy'
import { Route as AdminConcernsRouteImport } from './routes/admin.concerns'
import { Route as AdminBulkDispatchRouteImport } from './routes/admin.bulk-dispatch'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const WspIssuesRoute = WspIssuesRouteImport.update({
  id: '/wsp-issues',
  path: '/wsp-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const WspInTransitRoute = WspInTransitRouteImport.update({
  id: '/wsp-in-transit',
  path: '/wsp-in-transit',
  getParentRoute: () => rootRouteImport,
} as any)
const WdTransferRoute = WdTransferRouteImport.update({
  id: '/wd-transfer',
  path: '/wd-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const WdStockTrackRoute = WdStockTrackRouteImport.update({
  id: '/wd-stock-track',
  path: '/wd-stock-track',
  getParentRoute: () => rootRouteImport,
} as any)
const WdIssueTlRoute = WdIssueTlRouteImport.update({
  id: '/wd-issue-tl',
  path: '/wd-issue-tl',
  getParentRoute: () => rootRouteImport,
} as any)
const WdIssueRoute = WdIssueRouteImport.update({
  id: '/wd-issue',
  path: '/wd-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const WdRoute = WdRouteImport.update({
  id: '/wd',
  path: '/wd',
  getParentRoute: () => rootRouteImport,
} as any)
const TlRoute = TlRouteImport.update({
  id: '/tl',
  path: '/tl',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWdsRoute = MyWdsRouteImport.update({
  id: '/my-wds',
  path: '/my-wds',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const LossesRoute = LossesRouteImport.update({
  id: '/losses',
  path: '/losses',
  getParentRoute: () => rootRouteImport,
} as any)
const LossApprovalsRoute = LossApprovalsRouteImport.update({
  id: '/loss-approvals',
  path: '/loss-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcernsRoute = ConcernsRouteImport.update({
  id: '/concerns',
  path: '/concerns',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WdAdminUsersRoute = WdAdminUsersRouteImport.update({
  id: '/wd-admin/users',
  path: '/wd-admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHierarchyRoute = AdminHierarchyRouteImport.update({
  id: '/admin/hierarchy',
  path: '/admin/hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConcernsRoute = AdminConcernsRouteImport.update({
  id: '/admin/concerns',
  path: '/admin/concerns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBulkDispatchRoute = AdminBulkDispatchRouteImport.update({
  id: '/admin/bulk-dispatch',
  path: '/admin/bulk-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/concerns': typeof ConcernsRoute
  '/login': typeof LoginRoute
  '/loss-approvals': typeof LossApprovalsRoute
  '/losses': typeof LossesRoute
  '/movements': typeof MovementsRoute
  '/my-wds': typeof MyWdsRoute
  '/receive': typeof ReceiveRoute
  '/stock': typeof StockRoute
  '/tl': typeof TlRoute
  '/wd': typeof WdRoute
  '/wd-issue': typeof WdIssueRoute
  '/wd-issue-tl': typeof WdIssueTlRoute
  '/wd-stock-track': typeof WdStockTrackRoute
  '/wd-transfer': typeof WdTransferRoute
  '/wsp-in-transit': typeof WspInTransitRoute
  '/wsp-issues': typeof WspIssuesRoute
  '/admin/bulk-dispatch': typeof AdminBulkDispatchRoute
  '/admin/concerns': typeof AdminConcernsRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/users': typeof AdminUsersRoute
  '/wd-admin/users': typeof WdAdminUsersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/concerns': typeof ConcernsRoute
  '/login': typeof LoginRoute
  '/loss-approvals': typeof LossApprovalsRoute
  '/losses': typeof LossesRoute
  '/movements': typeof MovementsRoute
  '/my-wds': typeof MyWdsRoute
  '/receive': typeof ReceiveRoute
  '/stock': typeof StockRoute
  '/tl': typeof TlRoute
  '/wd': typeof WdRoute
  '/wd-issue': typeof WdIssueRoute
  '/wd-issue-tl': typeof WdIssueTlRoute
  '/wd-stock-track': typeof WdStockTrackRoute
  '/wd-transfer': typeof WdTransferRoute
  '/wsp-in-transit': typeof WspInTransitRoute
  '/wsp-issues': typeof WspIssuesRoute
  '/admin/bulk-dispatch': typeof AdminBulkDispatchRoute
  '/admin/concerns': typeof AdminConcernsRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/users': typeof AdminUsersRoute
  '/wd-admin/users': typeof WdAdminUsersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/concerns': typeof ConcernsRoute
  '/login': typeof LoginRoute
  '/loss-approvals': typeof LossApprovalsRoute
  '/losses': typeof LossesRoute
  '/movements': typeof MovementsRoute
  '/my-wds': typeof MyWdsRoute
  '/receive': typeof ReceiveRoute
  '/stock': typeof StockRoute
  '/tl': typeof TlRoute
  '/wd': typeof WdRoute
  '/wd-issue': typeof WdIssueRoute
  '/wd-issue-tl': typeof WdIssueTlRoute
  '/wd-stock-track': typeof WdStockTrackRoute
  '/wd-transfer': typeof WdTransferRoute
  '/wsp-in-transit': typeof WspInTransitRoute
  '/wsp-issues': typeof WspIssuesRoute
  '/admin/bulk-dispatch': typeof AdminBulkDispatchRoute
  '/admin/concerns': typeof AdminConcernsRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/users': typeof AdminUsersRoute
  '/wd-admin/users': typeof WdAdminUsersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/concerns'
    | '/login'
    | '/loss-approvals'
    | '/losses'
    | '/movements'
    | '/my-wds'
    | '/receive'
    | '/stock'
    | '/tl'
    | '/wd'
    | '/wd-issue'
    | '/wd-issue-tl'
    | '/wd-stock-track'
    | '/wd-transfer'
    | '/wsp-in-transit'
    | '/wsp-issues'
    | '/admin/bulk-dispatch'
    | '/admin/concerns'
    | '/admin/hierarchy'
    | '/admin/users'
    | '/wd-admin/users'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/concerns'
    | '/login'
    | '/loss-approvals'
    | '/losses'
    | '/movements'
    | '/my-wds'
    | '/receive'
    | '/stock'
    | '/tl'
    | '/wd'
    | '/wd-issue'
    | '/wd-issue-tl'
    | '/wd-stock-track'
    | '/wd-transfer'
    | '/wsp-in-transit'
    | '/wsp-issues'
    | '/admin/bulk-dispatch'
    | '/admin/concerns'
    | '/admin/hierarchy'
    | '/admin/users'
    | '/wd-admin/users'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/concerns'
    | '/login'
    | '/loss-approvals'
    | '/losses'
    | '/movements'
    | '/my-wds'
    | '/receive'
    | '/stock'
    | '/tl'
    | '/wd'
    | '/wd-issue'
    | '/wd-issue-tl'
    | '/wd-stock-track'
    | '/wd-transfer'
    | '/wsp-in-transit'
    | '/wsp-issues'
    | '/admin/bulk-dispatch'
    | '/admin/concerns'
    | '/admin/hierarchy'
    | '/admin/users'
    | '/wd-admin/users'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ConcernsRoute: typeof ConcernsRoute
  LoginRoute: typeof LoginRoute
  LossApprovalsRoute: typeof LossApprovalsRoute
  LossesRoute: typeof LossesRoute
  MovementsRoute: typeof MovementsRoute
  MyWdsRoute: typeof MyWdsRoute
  ReceiveRoute: typeof ReceiveRoute
  StockRoute: typeof StockRoute
  TlRoute: typeof TlRoute
  WdRoute: typeof WdRoute
  WdIssueRoute: typeof WdIssueRoute
  WdIssueTlRoute: typeof WdIssueTlRoute
  WdStockTrackRoute: typeof WdStockTrackRoute
  WdTransferRoute: typeof WdTransferRoute
  WspInTransitRoute: typeof WspInTransitRoute
  WspIssuesRoute: typeof WspIssuesRoute
  AdminBulkDispatchRoute: typeof AdminBulkDispatchRoute
  AdminConcernsRoute: typeof AdminConcernsRoute
  AdminHierarchyRoute: typeof AdminHierarchyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  WdAdminUsersRoute: typeof WdAdminUsersRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wsp-issues': {
      id: '/wsp-issues'
      path: '/wsp-issues'
      fullPath: '/wsp-issues'
      preLoaderRoute: typeof WspIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wsp-in-transit': {
      id: '/wsp-in-transit'
      path: '/wsp-in-transit'
      fullPath: '/wsp-in-transit'
      preLoaderRoute: typeof WspInTransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wd-transfer': {
      id: '/wd-transfer'
      path: '/wd-transfer'
      fullPath: '/wd-transfer'
      preLoaderRoute: typeof WdTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wd-stock-track': {
      id: '/wd-stock-track'
      path: '/wd-stock-track'
      fullPath: '/wd-stock-track'
      preLoaderRoute: typeof WdStockTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wd-issue-tl': {
      id: '/wd-issue-tl'
      path: '/wd-issue-tl'
      fullPath: '/wd-issue-tl'
      preLoaderRoute: typeof WdIssueTlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wd-issue': {
      id: '/wd-issue'
      path: '/wd-issue'
      fullPath: '/wd-issue'
      preLoaderRoute: typeof WdIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wd': {
      id: '/wd'
      path: '/wd'
      fullPath: '/wd'
      preLoaderRoute: typeof WdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tl': {
      id: '/tl'
      path: '/tl'
      fullPath: '/tl'
      preLoaderRoute: typeof TlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-wds': {
      id: '/my-wds'
      path: '/my-wds'
      fullPath: '/my-wds'
      preLoaderRoute: typeof MyWdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losses': {
      id: '/losses'
      path: '/losses'
      fullPath: '/losses'
      preLoaderRoute: typeof LossesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loss-approvals': {
      id: '/loss-approvals'
      path: '/loss-approvals'
      fullPath: '/loss-approvals'
      preLoaderRoute: typeof LossApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerns': {
      id: '/concerns'
      path: '/concerns'
      fullPath: '/concerns'
      preLoaderRoute: typeof ConcernsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wd-admin/users': {
      id: '/wd-admin/users'
      path: '/wd-admin/users'
      fullPath: '/wd-admin/users'
      preLoaderRoute: typeof WdAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hierarchy': {
      id: '/admin/hierarchy'
      path: '/admin/hierarchy'
      fullPath: '/admin/hierarchy'
      preLoaderRoute: typeof AdminHierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/concerns': {
      id: '/admin/concerns'
      path: '/admin/concerns'
      fullPath: '/admin/concerns'
      preLoaderRoute: typeof AdminConcernsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bulk-dispatch': {
      id: '/admin/bulk-dispatch'
      path: '/admin/bulk-dispatch'
      fullPath: '/admin/bulk-dispatch'
      preLoaderRoute: typeof AdminBulkDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ConcernsRoute: ConcernsRoute,
  LoginRoute: LoginRoute,
  LossApprovalsRoute: LossApprovalsRoute,
  LossesRoute: LossesRoute,
  MovementsRoute: MovementsRoute,
  MyWdsRoute: MyWdsRoute,
  ReceiveRoute: ReceiveRoute,
  StockRoute: StockRoute,
  TlRoute: TlRoute,
  WdRoute: WdRoute,
  WdIssueRoute: WdIssueRoute,
  WdIssueTlRoute: WdIssueTlRoute,
  WdStockTrackRoute: WdStockTrackRoute,
  WdTransferRoute: WdTransferRoute,
  WspInTransitRoute: WspInTransitRoute,
  WspIssuesRoute: WspIssuesRoute,
  AdminBulkDispatchRoute: AdminBulkDispatchRoute,
  AdminConcernsRoute: AdminConcernsRoute,
  AdminHierarchyRoute: AdminHierarchyRoute,
  AdminUsersRoute: AdminUsersRoute,
  WdAdminUsersRoute: WdAdminUsersRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
